[package]
name = "quipuu-cbom"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "CycloneDX 1.6/1.7 CBOM emitter and validator for quipuu."

[dependencies]
quipuu-core = { path = "../core", version = "0.1.0" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
jsonschema.workspace = true
uuid.workspace = true

[dev-dependencies]
quipuu-scan-source = { path = "../scan-source", version = "0.1.0" }
