//! `cryptoscope init [PATH]` — onboarding wizard.
//!
//! Detects ecosystems from manifest files in the target directory, asks 5
//! questions via stdin (silently uses defaults when stdin is not a TTY or is
//! closed), and writes `.cryptoscope.toml`.

use std::io::{self, BufRead, Write};
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use crate::config::{
    CONFIG_FILENAME, Config, DiagnosticsConfig, OutputConfig, PolicyConfig, ScanConfig,
};

/// Entry point called from `main`.
pub fn run(path: PathBuf) -> ExitCode {
    let root = if path.as_os_str().is_empty() {
        std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."))
    } else {
        path
    };

    let config_path = root.join(CONFIG_FILENAME);
    if config_path.exists() {
        eprintln!(
            "cryptoscope: {} already exists — delete it first to re-initialise.",
            config_path.display()
        );
        return ExitCode::FAILURE;
    }

    let detected = detect_ecosystems(&root);
    let stdin_is_tty = is_stdin_interactive();

    println!("cryptoscope init — project setup wizard");
    println!("Working directory: {}", root.display());

    if detected.languages.is_empty() {
        println!("No recognised manifest files found at top 2 levels.");
    } else {
        println!("Detected ecosystems: {}", detected.languages.join(", "));
    }

    let config = wizard(&detected, stdin_is_tty);

    let toml_str = match toml::to_string_pretty(&config) {
        Ok(s) => format!("# Generated by `cryptoscope init`\n{s}"),
        Err(e) => {
            eprintln!("cryptoscope: failed to serialise config: {e}");
            return ExitCode::FAILURE;
        }
    };

    if let Err(e) = std::fs::write(&config_path, &toml_str) {
        eprintln!(
            "cryptoscope: failed to write {}: {e}",
            config_path.display()
        );
        return ExitCode::FAILURE;
    }

    println!("\nWrote {}", config_path.display());
    println!("\nNext steps:");
    println!(
        "  cryptoscope scan {}           — run a full scan",
        root.display()
    );
    println!(
        "  open {}  — view the HTML report after scanning",
        root.join(&config.output.html).display()
    );
    println!(
        "  Commit {} to share settings with your team.",
        CONFIG_FILENAME
    );

    ExitCode::SUCCESS
}

// ── Detection ────────────────────────────────────────────────────────────────

struct Detected {
    /// Human-readable language/ecosystem names.
    languages: Vec<String>,
    /// Corresponding scan-language tokens for the config.
    lang_tokens: Vec<String>,
}

/// Scan the top 2 directory levels for well-known manifest files.
fn detect_ecosystems(root: &Path) -> Detected {
    struct Manifest {
        file: &'static str,
        label: &'static str,
        token: &'static str,
    }

    let manifests = [
        Manifest {
            file: "requirements.txt",
            label: "Python (pypi)",
            token: "python",
        },
        Manifest {
            file: "setup.py",
            label: "Python (pypi)",
            token: "python",
        },
        Manifest {
            file: "pyproject.toml",
            label: "Python (pypi)",
            token: "python",
        },
        Manifest {
            file: "package.json",
            label: "Node.js (npm)",
            token: "javascript",
        },
        Manifest {
            file: "pom.xml",
            label: "Java (maven)",
            token: "java",
        },
        Manifest {
            file: "build.gradle",
            label: "Java (gradle)",
            token: "java",
        },
        Manifest {
            file: "Cargo.toml",
            label: "Rust (crates.io)",
            token: "rust",
        },
        Manifest {
            file: "go.mod",
            label: "Go (modules)",
            token: "go",
        },
        Manifest {
            file: "*.csproj",
            label: "C# (.NET)",
            token: "csharp",
        },
    ];

    let mut languages: Vec<String> = Vec::new();
    let mut tokens: Vec<String> = Vec::new();

    // Check root and one level deep.
    let mut dirs_to_check: Vec<PathBuf> = vec![root.to_path_buf()];
    if let Ok(entries) = std::fs::read_dir(root) {
        for entry in entries.flatten() {
            if entry.path().is_dir() {
                dirs_to_check.push(entry.path());
            }
        }
    }

    for m in &manifests {
        let found = dirs_to_check.iter().any(|dir| {
            if m.file.starts_with('*') {
                // Glob: *.ext — check any file with matching extension.
                let ext = &m.file[1..]; // e.g. ".csproj"
                std::fs::read_dir(dir)
                    .map(|rd| {
                        rd.flatten()
                            .any(|e| e.file_name().to_string_lossy().ends_with(ext))
                    })
                    .unwrap_or(false)
            } else {
                dir.join(m.file).exists()
            }
        });

        if found && !tokens.contains(&m.token.to_string()) {
            languages.push(m.label.to_string());
            tokens.push(m.token.to_string());
        }
    }

    Detected {
        languages,
        lang_tokens: tokens,
    }
}

// ── Wizard ───────────────────────────────────────────────────────────────────

fn wizard(detected: &Detected, interactive: bool) -> Config {
    // Q1: languages to scan
    let scan_languages = if detected.languages.is_empty() {
        Vec::new()
    } else {
        let prompt = format!(
            "We detected: {}. Scan these? [Y/n]: ",
            detected.languages.join(", ")
        );
        if prompt_yes(&prompt, true, interactive) {
            detected.lang_tokens.clone()
        } else {
            Vec::new()
        }
    };

    // Q2: output formats
    let (html_out, sarif_out, cbom_out, summary_out) = if prompt_yes(
        "Output formats: HTML + SARIF + CBOM + summary JSON? [Y/n]: ",
        true,
        interactive,
    ) {
        (
            "reports/cryptoscope.html".to_string(),
            "reports/cryptoscope.sarif".to_string(),
            "reports/cryptoscope.cbom.json".to_string(),
            "reports/cryptoscope.summary.json".to_string(),
        )
    } else {
        (String::new(), String::new(), String::new(), String::new())
    };

    // Q3: policy preset
    let preset = prompt_choice(
        "Policy preset — nist-default / cnsa-2 / strict? [nist-default]: ",
        &["nist-default", "cnsa-2", "strict"],
        "nist-default",
        interactive,
    );

    // Q4: include test files
    let include_tests = prompt_yes("Include test files? [y/N]: ", false, interactive);
    let exclude_paths: Vec<String> = if include_tests {
        vec!["vendor".into(), "target".into(), "node_modules".into()]
    } else {
        vec![
            "tests".into(),
            "vendor".into(),
            "target".into(),
            "node_modules".into(),
        ]
    };

    // Q5: pre-commit hook marker
    let add_hook = prompt_yes("Add a pre-commit hook marker? [y/N]: ", false, interactive);
    if add_hook {
        println!("  [marker] Pre-commit hook requested — Phase 19d will wire up the real hook.");
    }

    Config {
        scan: ScanConfig {
            paths: vec!["src".into(), "lib".into()],
            exclude_paths,
            languages: scan_languages,
        },
        output: OutputConfig {
            html: html_out,
            sarif: sarif_out,
            cbom: cbom_out,
            summary_json: summary_out,
        },
        policy: PolicyConfig {
            preset,
            include_safe: false,
        },
        diagnostics: DiagnosticsConfig { show_errors: false },
    }
}

// ── Prompt helpers ────────────────────────────────────────────────────────────

fn is_stdin_interactive() -> bool {
    #[cfg(unix)]
    {
        libc_isatty(0)
    }
    #[cfg(not(unix))]
    {
        false
    }
}

#[cfg(unix)]
fn libc_isatty(fd: i32) -> bool {
    unsafe extern "C" {
        fn isatty(fd: i32) -> i32;
    }
    unsafe { isatty(fd) != 0 }
}

/// Ask a yes/no question. Uses `default` when stdin is closed or non-interactive.
fn prompt_yes(question: &str, default: bool, interactive: bool) -> bool {
    if !interactive {
        return default;
    }
    print!("{question}");
    let _ = io::stdout().flush();

    let mut line = String::new();
    let stdin = io::stdin();
    match stdin.lock().read_line(&mut line) {
        Ok(0) | Err(_) => return default, // EOF / error → use default
        Ok(_) => {}
    }
    let answer = line.trim().to_ascii_lowercase();
    if answer.is_empty() {
        return default;
    }
    answer.starts_with('y')
}

/// Ask a multiple-choice question; returns one of `choices` or `default`.
fn prompt_choice(question: &str, choices: &[&str], default: &str, interactive: bool) -> String {
    if !interactive {
        return default.to_string();
    }
    print!("{question}");
    let _ = io::stdout().flush();

    let mut line = String::new();
    let stdin = io::stdin();
    match stdin.lock().read_line(&mut line) {
        Ok(0) | Err(_) => return default.to_string(),
        Ok(_) => {}
    }
    let answer = line.trim().to_ascii_lowercase();
    if answer.is_empty() {
        return default.to_string();
    }
    choices
        .iter()
        .find(|&&c| c.to_ascii_lowercase() == answer)
        .map(|&c| c.to_string())
        .unwrap_or_else(|| default.to_string())
}
